language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip3 install .
script:
- pytest
deploy:
  provider: pypi
  on:
    tags: true
    branch: master
  user: '__token__'
  password:
    secure: qwEGIdHghnZRG4oxdg5jfIT9HysFT2okBf3FpXNrV6lBcWWkNtVSzPILwSpSM1B5ZbGw7wwV1mAbb/BYHwASnmQFExnPgDj5FKxoiISKqdOHq1+07hbAWCIOe3wPEj5VYVlsck0iB8nE8N8FceO5lvRB7ovdlLgc6cTqXyS3ENBY964STeCjTS0uEUFIgaEGZAzJowyc99LaaPkF/e6aOPsb4eN3qIJDGKtyvTae8GJcFDyfvS9abh5XWFQR6QIvu+LAn8qS/1IO4MGU0DQjApn5La3hjxnvzZ+kK3irjm/cEZxL60oXo2+qGUo/nUcTgzBGWDlal+qy5Mt0hKtG50bEinY8CZJioQ7HU2Vrn2WDdyA9DKsHHRgzQnh68LgmjkR5bG3mdQF+7A7Ap5MpJspSsEoOwjlJo1ntfG5E5U1GCQFMYGit28SdgLB51fXn0U3HDi0eWEZCH/gyNL8iy46KbzR8SnrpV+LJUaaBuqe84vnHDJ+xFUlWTeC8iAjdwewWJ/ESX/ZlMb8rb4sKm4GkS7qrt+sn0yKINhLIdJcJZhmV8qLhTviVtqGI1BvYrruMzsJJzpg6sHYbdKo2ZqHA6MIUiqsMVUL6vCbBLqwNoiyIQQXINfz0lQUIC4V/wQhq943f/D6tLfggrj1p1W7lQbmIanL4+V+Rf1N9Elk=
