language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip3 install .
script:
- pytest
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: ZMjnTKpp3lfP8vAi6MsRfsqBBKsacaeEM5KRkg8VwmERWHzdhGvHNrpK9360p71PekcAuJRhY/HKXK3EF/bo4N+Ks8tDjtY/DqzAhy/TaHTN4N04n6ha9W6PKq0Z/m3Kti9DBN8c+pEdyzxCgh17wClK8+3khJhyaTzowaqnc9cWm8EFJM/JFjFhExR4pT31rgJ5EEh0799vRClsr5FJG0UhIoISjgm4GAMee1iRLT/14DJfeWkA/DaqyxQh+m3rLjfJgOjn1nyuejzwY9hxGEhna8c1DwH+iU8L0q/xlQJLV+Hb28OGAYoQCYNjPuXndCTvxBL2zDqMYbIg5fmSQ6hGjYT0VVf6qQAfftEhp0w0u0Zji4TFdfCk3HQ0Xn6mr7rx71eCNKebbyDS/2IgTc2/o1yYVTY+SYf3VFiRJmO0n2cZklK3dmEdnJ18CG+AkeTZXYMUAh/NnqiG+ujyy2E/Ru6UuKQ3/1hqF+XHYWUIrFtVZGIWWBCGY3PKFbdyG6omI6n4+9hlTZPOzl3RWD293/Eza+a0vl2h1dHCB5j9ESc3Gb+lYkdAX9Zh1nOetvJ+jTmoEElTDmLWe0iPWvqtZXLjF/P0rys2alwruUjCV2yOEDERz+2DmnHhGhSd7dL2y1kLjJm8QDGBBnvIvIMf930hurLCXlAcRGYkWvk=
  skip_existing: true
  skip_cleanup: true
  distributions: 'sdist bdist_wheel'
