language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip3 install .
script:
- pytest
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: Ij/VGCRRyBuRx3+oUPMvKIZJczmtgflhMVXq6llOUyOAUXBw4TugfJjvgH1RO3cAyjMFFrFo+udWiyCPslZioTVXPftyw0MCL4rpU+Xs75p82IpUcZuYHSUTgYAV4P+axF+rQbo5cCjHNZAXS2hp2vSC4VO3oYlwdZjF4RYVS/MHxBIG5+W1FYwgmfZgwTEryXXKzyuirhVlCKHGKD5/6mgloy6UHyIrMLiC88ev2ABQAJM27e97tef5sz8+dTltvRj5LQ63JM8ujS8T/R6wiz2vZmgWf4JBWCftLwrWzPGXI579Di+D7QxFDMasPq2zGlyiZTgDWQ7/ne+qoOCF2wp1bKjyXxSPjzsPWrWgk0BR6yI8El3SWN9UuJRb4yHWvNGpnC4XjbPQ0CVNVb8x4PBrF13+XJ2qDtaGBINkmiz1J2ILJnaYMLSnF/xbbE9uIQ/JtCJ6103BUjvT2Q9CLO9FiywyGdKBArnU0COSDvJnRN/verE+cpDXxt2VfA2sSGbkQAw0jwEhr60kFQDkph/sCQ9K1jJmggW+mIsIOBPcOXNqFjVKLoWPt5UyQlF72rLFxvyy/e+IUqhWAPkA658pO40IHE2UEZ+xaP8PCSginrlyVvwX1siCKBYZdDFvUROEht3sKcckpvn6slUtBqP7yQ2uefkbUX9Bw8cNwh0=
  skip_existing: true
  skip_cleanup: true
  distributions: sdist bdist_wheel
